//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuTravel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelDetail()
        {
            this.Travels = new HashSet<Travel>();
        }
    
        public int TravelDetailsId { get; set; }
        public string TravelFrom { get; set; }
        public string TravelTo { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int ProjectId { get; set; }
        public string Purpose { get; set; }
        public string HotelName { get; set; }
        public string Address { get; set; }
        public string RoomType { get; set; }
        public string Occupancy { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<int> NumberOfNights { get; set; }
        public string InBoundFlightNameAndNumber { get; set; }
        public string InBoundAirport { get; set; }
        public string InBoundPNR { get; set; }
        public string OutBoundFlightNameAndNumber { get; set; }
        public string OutBoundAirport { get; set; }
        public string OutBoundPNR { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travel> Travels { get; set; }
    }
}
